# MySQL Database Configuration
host: "your_mysql_host"
port: 3306
pool-size: 10
password: ""
username: ""
database: ""
# Hologram Settings!
start-hologram:
  y-offset: 0.5
  hologram-name:
    - '&cParkour Prologue'
    - '&eStart'
end-hologram:
  y-offset: 0.5
  hologram-name:
    - '&cParkour Prologue'
    - '&cEnd'
checkpoint-hologram:
  y-offset: 0.5
  hologram-name:
    - '&e&lCheckPoint'
    - '&a%order%'